name: Trigger Frontend Build

on:
  push:
      branches:
        - main

jobs:
  build_in_repository_A:
    runs-on: ubuntu-latest
    env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - name: Install OpenSSL
        run: sudo apt-get install -y openssl
        
      - name: Calculate SHA-256 Hash
        id: hash
        run: echo -n "${{ secrets.AUTH_TOKEN }}" | openssl dgst -sha256 | awk '{print $2}'
      
      - name: Trigger Build via API
        env:
          HASHED_TOKEN: ${{ steps.hash.outputs.hash }}
        run: |
          curl -X POST \
          -H "x-github-event: Build" \
          -H "X-Hub-Signature-256: sha256=$HASHED_TOKEN" \
          http://localhost:3002/api/webhook