name: Trigger Frontend Build

on:
  push:
    branches:
      - main 

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SERVER_HOST }}
          repository: MaximeTheneau/MaximeTheneau-Portfolio-Next.git
          event-type: new-post 
