name: Trigger Frontend Build

on:
  push:
    branches:
      - main 

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        file_name: .env

        
    - name: Deploy Next.js frontend
      run: |
            ls
